name: dart_board_chat
description: Realtime Chat based on Firebase Firestore.
version: 1.2.0
homepage: https://dart-board.io

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.15+1
  cloud_firestore: ^2.5.1
  dart_board_locator: ^0.9.4+10
  dart_board_firebase_database: ^1.0.10
  dart_board_authentication: ^1.1.10
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.dart_board_chat_feature
    iosBundleIdentifier: com.example.dartBoardChatFeature
