name: dart_board_bloc
description: Bloc & Cubit Bindings for dart-board.io
homepage: https://dart-board.io
repository: https://github.com/ahammer/dart_board
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_board_core: ^0.9.13
  flutter_bloc: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.dart_board_bloc
    iosBundleIdentifier: com.example.dartBoardBloc
