name: dart_board_core
description: Feature Framework for Flutter. Provides a kernel that allows feature encapsulation, isolation and integration.
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board
version: 0.9.16+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  logging: ^1.0.1
  intl: ^0.17.0
  dart_board_widgets: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter  

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: io.dart-board.core
    iosBundleIdentifier: io.dart-board.core
