name: dart_board_locator
description: Redux extensions for Dart Board, exposes flutter_redux and dart redux, and wraps them in a decoration based API, allowing features their own Redux stores
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

version: 0.9.4+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:  
  flutter:
    sdk: flutter    
  dart_board_core: ^0.9.13
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.dart_board_redux
    iosBundleIdentifier: com.example.dartBoardRedux
