name: dart_board_canvas
description: Animated canvas feature - Use to mount animations to routes
homepage: https://dart-board.io
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.10

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.dart_board_canvas
    iosBundleIdentifier: com.example.dartBoardCanvas
