name: dart_board_template_app_bar_sidenav
description: A basic template example that works with the App Bar and SideNav and registered DartBoard routes using RouteView.
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

version: 0.9.4+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.16+3
  dart_board_locator: ^0.9.8
  logging: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: io.dart-board.appbar_sidenav
    iosBundleIdentifier: io.dart-board.appbar_sidenav
