name: dart_board_core_plugin
description: Plugin Bindings for Dart-Board
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board
version: 1.2.4


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.16+4
  dart_board_widgets: ^1.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  pigeon:

flutter:
  plugin:
    platforms:
      android:
        package: io.dartboard.dart_board_core_plugin
        pluginClass: DartBoardCorePlugin

