name: dart_board_firebase_analytics
description: Analytics binding and hooks for dart-board
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board
# Configure firebase as per firebase documents
# E.g. configure the runner's with your keys for this to work

version: 1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.16
  dart_board_firebase_core: ^1.4.0
  firebase_analytics: ^8.3.1
  dart_board_tracking: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.dart_board_authentication_google
    iosBundleIdentifier: com.example.dartBoardAuthenticationGoogle
