name: dart_board_minesweeper
description: A minesweeper implementation ported to DartBoard. It provides a Redux app state and a /minesweep route to play the game
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

version: 0.9.6+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  

  #For immutable data types (Prevents bugs, makes Redux easier)
  built_collection: ^5.0.0
  build_runner: ^2.0.3 
  built_value: ^8.0.6 
  built_value_generator: ^8.0.6 

  #For Date formatting
  intl: ^0.17.0 

  #For stricter static analysis
  pedantic: ^1.11.0

  dart_board_core: ^0.9.14
  dart_board_redux: ^0.9.2+7
  redux_thunk: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: io.dartboard.dart_board_minesweeper
    iosBundleIdentifier: io.dart-board.dartBoardMinesweeper
