name: dart_board_debug
description: The debug feature for Dart Board. Provides the /debug route which can give insight into the current system.
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

version: 0.9.4+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  dart_board_core: ^0.9.12+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  
flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.metalrain.dart_board_debug_extension
    iosBundleIdentifier: com.metalrain.dartBoardDebugExtension
