name: dart_board_tracking
description: Tracking interface for dart_board
homepage: https://dart-board.io
issue_tracker: https://github.com/ahammer/dart_board/issues
repository: https://github.com/ahammer/dart_board

version: 1.2.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_board_core: ^0.9.12+1
  dart_board_locator: ^0.9.4+4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
    androidPackage: com.example.dart_board_authentication
    iosBundleIdentifier: com.example.dartBoardAuthentication
